spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:mysql://localhost:3306/any_db?serverTimezone=Asia/Shanghai&useCharater=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
application:
  version: 1.4
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/
