spring:
  application:
    name: movie-service
server:
  port: 2001
application:
  version: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/