spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:mysql://localhost:3306/any_db
    driver-class-name: com.mysql.jdbc.Driver
    username: root
server:
  port: 2001
application:
  version: 1.4
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/
