spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:mysql://localhost:3306/any_db?serverTimezone=Asia/Shanghai&useCharater=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
application:
  version: 1.4
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/
---
spring:
  profiles: zone-2
eureka:
  client:
    region: beijing
    availability-zones:
      beijing: zone-1,zone-2
    service-url:
      zone-1: http://peer1:1001/eureka/
      zone-2: http://peer2:1002/eureka/
  instance:
    metadata-map:
      zone: zone-2
---
spring:
  profiles: zone-1
eureka:
  client:
    region: beijing
    availability-zones:
      beijing: zone-1,zone-2
    service-url:
      zone-1: http://peer1:1001/eureka/
      zone-2: http://peer2:1002/eureka/
  instance:
    metadata-map:
      zone: zone-1